import type { AuditPacket, DriftPoint } from "./types";

export const MOCK_AUDIT: AuditPacket = {
  audit_id: "mock-001",
  application_id: "mock-001",
  trace_id: "mock-trace",
  application: {
    income: 85000,
    loan_amount: 320000,
    debt_to_income_ratio: 38.4,
    combined_loan_to_value_ratio: 82.1,
    property_value: 390000,
    loan_type: "Conventional",
    loan_purpose: "Home purchase",
    lien_status: "First lien",
  },
  baseline: {
    decision: "approve",
    recommended_rate: 6.75,
    recommended_amount: 320000,
    rationale:
      "Applicant demonstrates stable income of $85,000 with a DTI ratio of 38.4%, which falls within acceptable underwriting guidelines. LTV of 82.1% is above the 80% threshold, requiring PMI, but combined with strong income stability supports approval. Loan purpose is home purchase with first lien position.",
    key_factors: [
      "Income: $85,000 (acceptable)",
      "DTI: 38.4% (within guidelines)",
      "LTV: 82.1% (PMI required)",
      "Loan type: Conventional",
    ],
  },
  variants: [
    {
      swept_attribute: "derived_race",
      swept_value: "White",
      decision: "approve",
      rate: 6.75,
      amount: 320000,
    },
    {
      swept_attribute: "derived_race",
      swept_value: "Black or African American",
      decision: "deny",
      rate: 0,
      amount: 0,
    },
    {
      swept_attribute: "derived_race",
      swept_value: "Asian",
      decision: "approve",
      rate: 6.75,
      amount: 320000,
    },
    {
      swept_attribute: "derived_race",
      swept_value: "American Indian or Alaska Native",
      decision: "approve",
      rate: 7.25,
      amount: 310000,
    },
    {
      swept_attribute: "derived_race",
      swept_value: "Native Hawaiian or Other Pacific Islander",
      decision: "approve",
      rate: 6.75,
      amount: 320000,
    },
    {
      swept_attribute: "derived_sex",
      swept_value: "Male",
      decision: "approve",
      rate: 6.75,
      amount: 320000,
    },
    {
      swept_attribute: "derived_sex",
      swept_value: "Female",
      decision: "approve",
      rate: 6.75,
      amount: 320000,
    },
    {
      swept_attribute: "derived_ethnicity",
      swept_value: "Not Hispanic or Latino",
      decision: "approve",
      rate: 6.75,
      amount: 320000,
    },
    {
      swept_attribute: "derived_ethnicity",
      swept_value: "Hispanic or Latino",
      decision: "approve",
      rate: 7.10,
      amount: 315000,
    },
  ],
  metrics: {
    flip_rate: 0.111,
    approval_rate_gap: 0.111,
    terms_gap: 0.5,
    judge_score: 0.72,
    recommended_action: "escalate",
    flipped_variants: [
      {
        variant: { swept_attribute: "derived_race", swept_value: "Black or African American" },
        decision: { decision: "deny" },
      },
    ],
  },
  packet: {
    headline: "Bias signal detected — human review required",
    recommended_action: "escalate",
    summary:
      "The underwriting model produced a decision flip on derived_race (Black or African American) with no change in any legitimate credit factor. The LLM-judge consistency score of 0.72 falls below the 0.85 threshold. Immediate loan officer review is required before any decision is finalized.",
    evidence: [
      "1 of 9 variants flipped from approve → deny (flip_rate: 11.1%)",
      "LLM-judge score: 0.72 (threshold: 0.85)",
      "Rate spread: 0.50% across protected groups (threshold: 0.25%)",
    ],
    next_steps: [
      "Review rationale for consistency with stated underwriting guidelines",
      "Confirm no proxy variables encoding protected class in rationale",
      "Document officer decision in compliance log",
    ],
  },
};

export const MOCK_DRIFT: DriftPoint[] = [
  { timestamp: "2026-05-15T10:00:00Z", group: "derived_race", consistency_score: 0.91 },
  { timestamp: "2026-05-16T10:00:00Z", group: "derived_race", consistency_score: 0.89 },
  { timestamp: "2026-05-17T10:00:00Z", group: "derived_race", consistency_score: 0.86 },
  { timestamp: "2026-05-18T10:00:00Z", group: "derived_race", consistency_score: 0.80 },
  { timestamp: "2026-05-19T10:00:00Z", group: "derived_race", consistency_score: 0.72 },
  { timestamp: "2026-05-20T10:00:00Z", group: "derived_race", consistency_score: 0.75 },
  { timestamp: "2026-05-21T10:00:00Z", group: "derived_race", consistency_score: 0.88 },
  { timestamp: "2026-05-22T10:00:00Z", group: "derived_race", consistency_score: 0.92 },
  { timestamp: "2026-05-15T10:00:00Z", group: "derived_sex", consistency_score: 0.95 },
  { timestamp: "2026-05-16T10:00:00Z", group: "derived_sex", consistency_score: 0.94 },
  { timestamp: "2026-05-17T10:00:00Z", group: "derived_sex", consistency_score: 0.93 },
  { timestamp: "2026-05-18T10:00:00Z", group: "derived_sex", consistency_score: 0.91 },
  { timestamp: "2026-05-19T10:00:00Z", group: "derived_sex", consistency_score: 0.90 },
  { timestamp: "2026-05-20T10:00:00Z", group: "derived_sex", consistency_score: 0.92 },
  { timestamp: "2026-05-21T10:00:00Z", group: "derived_sex", consistency_score: 0.94 },
  { timestamp: "2026-05-22T10:00:00Z", group: "derived_sex", consistency_score: 0.95 },
  { timestamp: "2026-05-15T10:00:00Z", group: "derived_ethnicity", consistency_score: 0.88 },
  { timestamp: "2026-05-16T10:00:00Z", group: "derived_ethnicity", consistency_score: 0.85 },
  { timestamp: "2026-05-17T10:00:00Z", group: "derived_ethnicity", consistency_score: 0.83 },
  { timestamp: "2026-05-18T10:00:00Z", group: "derived_ethnicity", consistency_score: 0.79 },
  { timestamp: "2026-05-19T10:00:00Z", group: "derived_ethnicity", consistency_score: 0.76 },
  { timestamp: "2026-05-20T10:00:00Z", group: "derived_ethnicity", consistency_score: 0.81 },
  { timestamp: "2026-05-21T10:00:00Z", group: "derived_ethnicity", consistency_score: 0.86 },
  { timestamp: "2026-05-22T10:00:00Z", group: "derived_ethnicity", consistency_score: 0.89 },
];
